name: Waka Readme

on:
  schedule:
    - cron: '20 00 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN   }}
          SHOW_LINES_OF_CODE : "True"
          SHOW_PROFILE_VIEWS : "False"
          SHOW_LOC_CHART : "False"
          LOCALE: "en"
